spring:
  application:
    name: microservice-consumer-movie-fegin-hystrix-fallback
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
server:
  port: 8084