spring:
  application:
    name: microservice-consumer-movie-fegin-logging
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: true
server:
  port: 8084
logging:
  level:
    com.lic.fegin.UserFeignClient: DEBUG # 将Feign接口的日志级别设置为DEBUG，因为Feign的Logger.Level只对DEBUG作出响应